### ISSUE TITLE
Creating an AtomArray from atoms with optional annotations fails

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#279]
Creating a new atomarray from atoms containing extra fields produces an error. Please see the example below

```python
from biotite.database.rcsb import fetch
import biotite.structure.io as io
from biotite.structure import array

# get a pdb to test
file = fetch("5u6p", "pdb", ".")

# load an array without extra annotation and create a new arr from it's atoms
structure = io.load_structure(file)
atoms = [atom for atom in structure]
new_arr = array(atoms)  # works

# load an array with extra annotation
structure = io.load_structure(file, extra_fields=["atom_id"])
atoms = [atom for atom in structure]
new_arr = array(atoms)  # error

# > Traceback (most recent call last):
# >   File "test.py", line 16, in <module>
# >     new_arr = array(atoms)
# >   File "/home/😉/projects/biotite/src/biotite/structure/atoms.py", line 1175, in array
# >     array._annot[name][i] = atoms[i]._annot[name]
# > KeyError: 'atom_id'
```

**Comment by padix-key** [comment]
This looks surely like a bug. Thank for reporting, I will have a look.
