### ISSUE TITLE
Selenocysteine strikes again: AlphabetError in BlastWebApp

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#344]
One of my students encountered this and I was able to reproduce it with biotite version 0.29.0 as well as a fresh checkout from master/HEAD:

When performing a blast search with `BlastWebApp` on swissprot, the query sequence was a valid amino acid sequence. However, `BlastWebApp` encountered an `AlphabetError` when parsing the results:

Example Code to reproduce the error:
```python
from biotite.sequence.io import fasta
from biotite.application import blast
import biotite.sequence as seq

# Downloading sequence 
file_name = "sequence.txt"
fasta_file = fasta.FastaFile.read(file_name)
ref_seq = fasta.get_sequence(fasta_file)
print(f"U in sequence? {'U' in ref_seq}") # > False

#Find homologous proteins using NCBI Blast
# Search only the UniProt/SwissProt database
ref_seq = seq.ProteinSequence(ref_seq)
blast_app = blast.BlastWebApp("blastp", ref_seq, "swissprot")
blast_app.start()
blast_app.join() # > Alphabet Error
```

Tracelog
```
Traceback (most recent call last):
  File "biotite_bug.py", line 17, in <module>
    blast_app.join() 
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite-0.29.0-py3.7-linux-x86_64.egg/biotite/application/application.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite-0.29.0-py3.7-linux-x86_64.egg/biotite/application/application.py", line 153, in join
    self.evaluate()
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite-0.29.0-py3.7-linux-x86_64.egg/biotite/application/blast/webapp.py", line 346, in evaluate
    seq2 = ProteinSequence(seq2_str.replace("-", ""))
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite-0.29.0-py3.7-linux-x86_64.egg/biotite/sequence/seqtypes.py", line 473, in __init__
    super().__init__(sequence)
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite-0.29.0-py3.7-linux-x86_64.egg/biotite/sequence/sequence.py", line 147, in __init__
    self.symbols = sequence
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite-0.29.0-py3.7-linux-x86_64.egg/biotite/sequence/sequence.py", line 183, in symbols
    self._seq_code = alph.encode_multiple(value, dtype)
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite-0.29.0-py3.7-linux-x86_64.egg/biotite/sequence/alphabet.py", line 390, in encode_multiple
    return encode_chars(alphabet=self._symbols, symbols=symbols)
  File "src/biotite/sequence/codec.pyx", line 74, in biotite.sequence.codec.encode_chars
```

It sees like one of the sequences swissprot returned contains a `U` and BlastWebApp is not handling this properly yet.

Here is the query sequence to reproduce this [sequence.txt](https://github.com/biotite-dev/biotite/files/6929711/sequence.txt).
Also linking #232 here which was a similar issue.

**Comment by padix-key** [comment]
Thank you for the report. Yes, it is indeed related to the same issue. The lines causing this problem are

https://github.com/biotite-dev/biotite/blob/2cc0b67d78050336979b14ab6e4600a02cc771f8/src/biotite/application/blast/webapp.py#L345-L346

because the sequence string is given unchecked to the `ProteinSequence`, so `U` is not converted into `C`.
